[package]
name = "cryptopals-rs"
version = "0.1.0"
edition = "2021"
author = "shady@shadyproject.net"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "challenges"
path="src/lib.rs"

[dependencies]
base64 = "0.13.0"
counter = "0.5.2"
